service: ${env:PIPELINE_SERVICE_NAME}

custom:
  defaults:
    source:
      owner: santaswap
      repository: test
      branch: test

provider:
  name: aws
  stage: local
  runtime: nodejs6.10
  stackTags:
   repo: ${env:REPO_NAME}
   frigg: pipeline

functions:
  hello:
    handler: handler.hello

resources:
  Description: Frigg-generated CodePipeline for deploying the ${env:OWNER}/${env:REPO} serverless application

  Resources:

    Pipeline:
      Type: AWS::CodePipeline::Pipeline
      Properties:
        Name: ${env:OWNER}-${env:REPO}-${env:BRANCH}-pipeline
        ArtifactStore:
          Type: S3
          Location: { Ref: PipelineArtifactStore }
        RoleArn: { Fn::GetAtt: PipelineRole.Arn }
        Stages:
          
          # Application source stage
          - Name: Source
            Actions:
              - Name: Source
                RunOrder: 1
                ActionTypeId:
                  Category: Source
                  Owner: ThirdParty
                  Provider: GitHub
                  Version: 1
                Configuration:
                  Owner: ${env:OWNER}
                  Repo: ${env:REPO}
                  Branch: ${env:BRANCH}
                  OAuthToken: ${env:GITHUB_TOKEN}
                OutputArtifacts:
                  - Name: ApplicationArtifact
          
          # Application build stage
          - Name: Build
            Actions:
              - Name: Deploy
                RunOrder: 1
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                Configuration:
                  ProjectName: { Ref: CodeBuild }
                InputArtifacts:
                  - Name: ApplicationArtifact
                OutputArtifacts:
                  - Name: ApplicationBuildOutput

    CodeBuild:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: ${env:OWNER}-${env:REPO}-${env:BRANCH}-build
        Description: Application build project
        Source:
          Type: CODEPIPELINE
        Environment:
          Image: aws/codebuild/eb-nodejs-6.10.0-amazonlinux-64:4.0.0
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          EnvironmentVariables:
            - Name: STAGE
              Value: local
        Artifacts:
          Type: CODEPIPELINE
        ServiceRole: { Ref: CodeBuildRole }
        TimeoutInMinutes: 60

    PipelineArtifactStore:
      Type: AWS::S3::Bucket

    PipelineRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service:
                  - codepipeline.amazonaws.com
        Path: /
        Policies:
          - PolicyName: TODO
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: '*'
                  Resource: '*'

    CodeBuildRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                AWS:
                  Fn::Join:
                    - ''
                    - - 'arn:aws:iam::'
                      - Ref: AWS::AccountId
                      - :root
            - Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: codebuild.amazonaws.com
        Path: /
        Policies:
          - PolicyName: ANOTHER_TODO
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: '*'
                  Resource: '*'
